import Foundation
import Observation
import WebKit

/// Cookies for sites that need a login. Two sources are merged into the single
/// Netscape-format file yt-dlp reads (`cookiefile`):
///  - sites the user signs into in the in-app browser, snapshotted when they tap Done
///  - a cookies.txt the user imports (e.g. exported from a desktop browser)
///
/// Browser cookies are snapshotted rather than read live: WebKit may not have
/// flushed them to disk if the app is killed, and its cookie store can report
/// nothing until a web view has loaded it.
@MainActor
@Observable
final class CookieStore {
    struct Site: Identifiable, Hashable {
        var id: String { domain }
        let domain: String
        let count: Int
        let imported: Bool
    }

    nonisolated static let cookieFile = AppPaths.cookies.appendingPathComponent("cookies.txt")
    private static let browserFile = AppPaths.cookies.appendingPathComponent("browser.txt")
    private static let importedFile = AppPaths.cookies.appendingPathComponent("imported.txt")

    private(set) var sites: [Site] = []

    private var dataStore: WKWebsiteDataStore { .default() }

    init() {
        rebuild()
    }

    /// Snapshots the in-app browser's cookies; call after the user signs in.
    func captureBrowserCookies() async {
        let cookies = await dataStore.httpCookieStore.allCookies()
        // Merge so sites captured earlier survive even if WebKit has since lost them.
        let fresh = cookies.map(Self.netscapeLine)
        let freshKeys = Set(fresh.map(Self.key))
        let kept = Self.readLines(Self.browserFile).filter { !freshKeys.contains(Self.key($0)) }
        Self.write(kept + fresh, to: Self.browserFile)
        rebuild()
    }

    /// Imports a Netscape cookies.txt, replacing any previous import.
    func importFile(_ url: URL) throws {
        let accessing = url.startAccessingSecurityScopedResource()
        defer { if accessing { url.stopAccessingSecurityScopedResource() } }
        let lines = Self.cookieLines(in: try String(contentsOf: url, encoding: .utf8))
        guard !lines.isEmpty else {
            throw BridgeError(message: "That file doesn't contain any cookies in Netscape (cookies.txt) format.")
        }
        Self.write(lines, to: Self.importedFile)
        rebuild()
    }

    /// Signs out of one site: removes its snapshotted, imported and browser cookies.
    func remove(_ site: Site) async {
        for file in [Self.browserFile, Self.importedFile] {
            let remaining = Self.readLines(file).filter { Self.siteName(Self.domain(ofLine: $0)) != site.domain }
            Self.write(remaining, to: file)
        }
        let records = await dataStore.dataRecords(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes())
        let matching = records.filter { Self.siteName($0.displayName) == site.domain }
        await dataStore.removeData(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes(), for: matching)
        rebuild()
    }

    func removeAll() async {
        await dataStore.removeData(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes(), modifiedSince: .distantPast)
        try? FileManager.default.removeItem(at: Self.browserFile)
        try? FileManager.default.removeItem(at: Self.importedFile)
        rebuild()
    }

    /// Recomputes the site list and rewrites the merged file yt-dlp reads.
    private func rebuild() {
        let browser = Self.readLines(Self.browserFile)
        let imported = Self.readLines(Self.importedFile)

        var counts: [String: (count: Int, imported: Bool)] = [:]
        for (line, isImported) in browser.map({ ($0, false) }) + imported.map({ ($0, true) }) {
            let domain = Self.siteName(Self.domain(ofLine: line))
            counts[domain, default: (0, false)].count += 1
            if isImported { counts[domain]?.imported = true }
        }
        sites = counts.map { Site(domain: $0.key, count: $0.value.count, imported: $0.value.imported) }
            .sorted { $0.domain < $1.domain }

        if browser.isEmpty && imported.isEmpty {
            try? FileManager.default.removeItem(at: Self.cookieFile)
        } else {
            Self.write(["# Netscape HTTP Cookie File", "# Generated by Squirrel for iOS"] + browser + imported,
                       to: Self.cookieFile)
        }
    }

    private static func write(_ lines: [String], to url: URL) {
        do {
            try FileManager.default.createDirectory(at: AppPaths.cookies, withIntermediateDirectories: true)
            try (lines.joined(separator: "\n") + "\n").write(to: url, atomically: true, encoding: .utf8)
        } catch {
            print("Failed to write \(url.lastPathComponent): \(error)")
        }
    }

    private static func readLines(_ url: URL) -> [String] {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return [] }
        return cookieLines(in: text)
    }

    /// Identity of a cookie line: domain, path and name.
    private static func key(_ line: String) -> String {
        let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
        return [domain(ofLine: line), String(fields[2]), String(fields[5])].joined(separator: "|")
    }

    // MARK: - Netscape format

    private static func netscapeLine(_ cookie: HTTPCookie) -> String {
        let domain = cookie.domain
        let includeSubdomains = domain.hasPrefix(".") ? "TRUE" : "FALSE"
        let expiry = cookie.expiresDate.map { String(Int($0.timeIntervalSince1970)) } ?? "0"
        let prefix = cookie.isHTTPOnly ? "#HttpOnly_" : ""
        return [prefix + domain, includeSubdomains, cookie.path, cookie.isSecure ? "TRUE" : "FALSE",
                expiry, cookie.name, cookie.value].joined(separator: "\t")
    }

    private static func cookieLines(in text: String) -> [String] {
        text.components(separatedBy: .newlines).filter { line in
            let isComment = line.hasPrefix("#") && !line.hasPrefix("#HttpOnly_")
            return !isComment && line.split(separator: "\t", omittingEmptySubsequences: false).count == 7
        }
    }

    private static func domain(ofLine line: String) -> String {
        String(line.split(separator: "\t").first ?? "").replacingOccurrences(of: "#HttpOnly_", with: "")
    }

    /// ".m.youtube.com" -> "youtube.com", so a site's cookies group together.
    static func siteName(_ domain: String) -> String {
        let parts = domain.trimmingCharacters(in: CharacterSet(charactersIn: ".")).split(separator: ".")
        guard parts.count > 2 else { return parts.joined(separator: ".") }
        // Keep three labels for two-letter second-level domains like .co.uk.
        let keep = parts[parts.count - 2].count <= 3 && parts.last!.count == 2 ? 3 : 2
        return parts.suffix(keep).joined(separator: ".")
    }
}
