package com.natan.ytdlp.data

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import com.natan.ytdlp.python.BridgeException
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import java.io.File

/**
 * Cookies for sites that need a login, merged into the single Netscape-format
 * file yt-dlp reads: sites signed into in the in-app browser (snapshotted on
 * Done, as on iOS) and an imported cookies.txt.
 */
class CookieStore(private val context: Context) {
    data class Site(val domain: String, val count: Int, val imported: Boolean)

    companion object {
        fun cookieFile(context: Context) = File(context.filesDir, "cookies/cookies.txt")

        /** ".m.youtube.com" -> "youtube.com", so a site's cookies group together. */
        fun siteName(domain: String): String {
            val parts = domain.trim('.').split('.')
            if (parts.size <= 2) return parts.joinToString(".")
            // Keep three labels for two-letter country domains like .co.uk
            val keep = if (parts[parts.size - 2].length <= 3 && parts.last().length == 2) 3 else 2
            return parts.takeLast(keep).joinToString(".")
        }
    }

    private val dir = File(context.filesDir, "cookies")
    private val browserFile = File(dir, "browser.txt")
    private val importedFile = File(dir, "imported.txt")

    private val _sites = MutableStateFlow<List<Site>>(emptyList())
    val sites: StateFlow<List<Site>> = _sites

    init {
        rebuild()
    }

    /**
     * Snapshots the in-app browser's cookies for the hosts visited while signing in.
     * Android's CookieManager only exposes name=value pairs, so each is stored
     * for the whole site, valid for a year.
     */
    fun captureBrowserCookies(hosts: Collection<String>) {
        val manager = CookieManager.getInstance()
        manager.flush()
        val expiry = System.currentTimeMillis() / 1000 + 365 * 24 * 3600
        val fresh = hosts.flatMap { host -> setOf(host, "www.${siteName(host)}", siteName(host)) }.distinct()
            .flatMap { host ->
                val header = manager.getCookie("https://$host/") ?: return@flatMap emptyList()
                header.split(';').mapNotNull { pair ->
                    val name = pair.substringBefore('=').trim()
                    val value = pair.substringAfter('=', "").trim()
                    if (name.isEmpty()) null
                    else listOf(".${siteName(host)}", "TRUE", "/", "TRUE", "$expiry", name, value).joinToString("\t")
                }
            }
        val freshKeys = fresh.map(::key).toSet()
        val kept = readLines(browserFile).filterNot { key(it) in freshKeys }
        write(kept + fresh.distinctBy(::key), browserFile)
        rebuild()
    }

    fun importFile(uri: Uri) {
        val text = context.contentResolver.openInputStream(uri)?.bufferedReader()?.use { it.readText() }.orEmpty()
        val lines = cookieLines(text)
        if (lines.isEmpty()) {
            throw BridgeException("That file doesn't contain any cookies in Netscape (cookies.txt) format.")
        }
        write(lines, importedFile)
        rebuild()
    }

    fun remove(site: Site) {
        for (file in listOf(browserFile, importedFile)) {
            write(readLines(file).filterNot { siteName(domainOf(it)) == site.domain }, file)
        }
        // Also sign the in-app browser out of that site
        val manager = CookieManager.getInstance()
        manager.getCookie("https://${site.domain}/")?.split(';')?.forEach { pair ->
            val name = pair.substringBefore('=').trim()
            manager.setCookie("https://${site.domain}/", "$name=; Max-Age=0; Domain=.${site.domain}; Path=/")
        }
        manager.flush()
        rebuild()
    }

    fun removeAll() {
        CookieManager.getInstance().removeAllCookies(null)
        browserFile.delete()
        importedFile.delete()
        rebuild()
    }

    private fun rebuild() {
        val browser = readLines(browserFile)
        val imported = readLines(importedFile)
        val counts = linkedMapOf<String, Pair<Int, Boolean>>()
        browser.forEach { line ->
            val site = siteName(domainOf(line))
            counts[site] = (counts[site]?.first ?: 0) + 1 to (counts[site]?.second ?: false)
        }
        imported.forEach { line ->
            val site = siteName(domainOf(line))
            counts[site] = (counts[site]?.first ?: 0) + 1 to true
        }
        _sites.value = counts.map { (domain, value) -> Site(domain, value.first, value.second) }.sortedBy { it.domain }

        val out = cookieFile(context)
        if (browser.isEmpty() && imported.isEmpty()) {
            out.delete()
        } else {
            write(listOf("# Netscape HTTP Cookie File", "# Generated by yt-dlp for Android") + browser + imported, out)
        }
    }

    private fun write(lines: List<String>, file: File) {
        file.parentFile?.mkdirs()
        file.writeText(lines.joinToString("\n", postfix = "\n"))
    }

    private fun readLines(file: File) = if (file.exists()) cookieLines(file.readText()) else emptyList()

    private fun cookieLines(text: String) = text.lines().filter { line ->
        val isComment = line.startsWith("#") && !line.startsWith("#HttpOnly_")
        !isComment && line.split('\t').size == 7
    }

    private fun domainOf(line: String) = line.substringBefore('\t').removePrefix("#HttpOnly_")

    private fun key(line: String): String {
        val fields = line.split('\t')
        return "${domainOf(line)}|${fields[2]}|${fields[5]}"
    }
}
